### PR TITLE
Fix color piracy

### LINKED ISSUE #36: Fix type piracy with Colors.RGB
Colors.RGB gets methods for string and symbols in GridVisualizeTools.
This is type piracy. May be can be replace by parse() (see Colors.jl docs).

### PR DESCRIPTION
**Pull request by jpthiele**
This removes any use of the type pirated `RGB` and fixes #36

### CODE REVIEW

File: src/makie.jl [hunk 1]
```diff
@@ -363,22 +363,30 @@ function scalarplot!(ctx, TP::Type{MakieType}, ::Type{Val{1}}, grids, parentgrid
     end
 
     function update_lines(ctx, newrange)
+	# No uniform method in Colors to create a color from either tuple or symbol
+        rgbcol = Colors.RGB{Float64}(0,0,0)
+        if ctx[:color] isa Tuple{Float64,Float64,Float64}
+          rgbcol = RGB(ctx[:color][1],ctx[:color][2],ctx[:color][3])
+        else
+          rgbcol = parse(Colors.RGB{Float64},ctx[:color])
+        end
```
Comment (jpthiele) [inline src/makie.jl:372]: @WIAS-PDELib/pdelib-developers I am very unhappy with this part myself but Colors is not happy with assuming a tuple is RGB.
I see two ways around this depending on downstream usage.
1. Don't assume users want RGB and make them type it explicitly when supplying individual values, i.e. `color = RGB(r,g,b)`
2. Keep this somewhat ugly snippet in

Comment (jpthiele) [reply src/makie.jl:372]: I changed the default in `dispatch.jl` to `RGB(0.0, 0.0, 0.0)` which makes the tests pass without that snippet.

Comment (j-fu) [reply src/makie.jl:372]: I don't think this issue is worth a breaking change. 

One possibility to avoid ugly code here might be some "MyRGBColor" in GridVisualizeTools which takes RGB, Tuples, strings, symbols.

**Comment by jpthiele** [comment]
Notes from short in-person discussion. 
We will keep the workaround with `isa` for now but issue a `depwarn` to let users know that setting a color by tuple will be removed in the next major release (whenever that may be)

**Review by j-fu — APPROVED** [review]
